### PR TITLE
Enable Cargo's sparse registry for CI

### LINKED ISSUE #260: Enable sparse registry for CI
The new sparse registry for cargo can speed up the installation a bit in some cases.
I thought I already enabled it last time I checked the CI workflows, but apparently not.

This issue should serve me as a reminder so I don't forget tomorrow

### PR DESCRIPTION
**Pull request by TimJentzsch**
Closes #260.

This PR enables Cargo's sparse registry which can speed up the dependency updates in some cases.

The also <https://blog.rust-lang.org/inside-rust/2023/01/30/cargo-sparse-protocol.html>.

Depends on #262 for fixing CI.

### CODE REVIEW

**Comment by janhohenheim** [comment]
Looks like this saves us 3-4 mins on `test-native-docs` :)

**Comment by TimJentzsch** [comment]
> Looks like this saves us 3-4 mins on test-native-docs :D

That's more than I expected.
Are you sure this change isn't also caused by the cache?
I.e. that we got a cache miss in the previous run?

**Comment by janhohenheim** [comment]
Could be. In my experience, `test-native-docs` is a bit weird in general judging by what does and does not factor into its caching.

**Comment by TimJentzsch** [comment]
I also think parts of the cache are not working correctly for some of our CI workflows...
It's really strange how long CI is taking for us

**Pull request merged**
