### PR TITLE
Enable full-screen

### LINKED ISSUE #252: Make game fullscreen
Most games work better when they use fullscreen by default.
Especially in the browser this will look better.

## Resources

- [Bevy example on Window settings](https://github.com/bevyengine/bevy/blob/main/examples/window/window_settings.rs)
- [Bevy `WindowMode`](https://docs.rs/bevy/latest/bevy/window/enum.WindowMode.html)

### PR DESCRIPTION
**Pull request by TimJentzsch**
Closes #252.

This PR enables full-screen for both native and web builds.

Unfortunately this makes the web page a bit less pretty until the game loads in.
I propose to fix that with a proper loading screen (in HTML/JS), I have a prototype for that here: <https://github.com/ramirezmike/game_off_2022/pull/1>.
That's a topic for a future PR though.

I also added a (very primitive) exit button to the pause menu so that you don't get stuck in the game on native.

### CODE REVIEW

**Comment by TimJentzsch** [comment]
Do you prefer Fullscreen or Borderless Window as a default?

**Comment by janhohenheim** [comment]
Borderless window please :)

**Comment by janhohenheim** [comment]
I realize this is still a draft, but just in case, FYI: you remove `--game-ui-height` from the css, but the code still references it.

**Comment by TimJentzsch** [comment]
@janhohenheim This should be ready to review now.
The quit button is ugly and the quit on WASM a bit hacky, but it seems to work :)

**Comment by janhohenheim** [comment]
LGTM!

**Pull request merged**
