### PR TITLE
ported dev window to bevy_editor_plz

### PR DESCRIPTION
**Pull request by PhaestusFox**
I saw issue #113 and decided to do it.
currently, this is more of a draft implementation since It is missing a key detail and there is at least one bug that should probably be fixed before a full merge.

I also made bevy_editor_pls open on q and not e so it doesn't open when you talk to the NPC

I don't know how to open a floating window outside of using the top bar with bevy_editor_plz so I removed the toggle code but this does mean you still get user input when the window is open.

there also is a bug that the menu will toggle from its open state when you close the escape menu, this would not be a problem if it only close when closing the menu but it will actually reopen it if you close it before hitting escape again. also only does it when closing the scape menu not opening it. I think this has to do with how you are telling egui to toggle the escape menu

hope this helps you get started since in the issue you were planning to do some sort of delayed update because you need multiple mutable world access but this doesn't seem to be the case.

### CODE REVIEW

**Comment by janhohenheim** [comment]
Thanks, I'll get on finishing the open points :)
Hehe, I see that the dialog and editor being on the same key is bothersome. The reason I never noticed is that I use the Workman keyboard layout and `bevy_editor_pls` doesn't use `ScanCode`s yet (https://github.com/jakobhellermann/bevy_editor_pls/issues/62), so for me they aren't on the same key at all! 😄

**Comment by janhohenheim** [comment]
Update: I finished your work in https://github.com/janhohenheim/foxtrot/pull/176; I quite like how it works now, thanks :)
I cannot reproduce the described interaction with the pause screen on my macOS. Can you confirm whether this still happens on `main`?

**Comment by PhaestusFox** [comment]
the bug is definitely still there, I did some further testing and if you click the arrow it won't toggle till you click again or hit escape I have a video showing this off. I think this is probably a redraw issue, and hitting escape forces the redraw but I don't know how egui works at that level


https://user-images.githubusercontent.com/75610846/221099959-35ba85c3-ddc0-4fcb-a511-906c69b86565.mov

**Comment by janhohenheim** [comment]
Oooh I see the problem.
Yeah, that seems like a weird issue 😅 Opting to leave it for the moment since this looks like a rabbit hole to get into for a very minor bug.

**Pull request merged**
